# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userInterface.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LaserCalculator(object):
    def setupUi(self, LaserCalculator):
        LaserCalculator.setObjectName("LaserCalculator")
        LaserCalculator.resize(700, 600)
        self.centralwidget = QtWidgets.QWidget(LaserCalculator)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 80, 241, 492))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.transmittingPower = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.transmittingPower.setObjectName("transmittingPower")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.transmittingPower)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.wavelength = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.wavelength.setObjectName("wavelength")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.wavelength)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.divergenceAngle = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.divergenceAngle.setObjectName("divergenceAngle")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.divergenceAngle)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.linkRange = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.linkRange.setObjectName("linkRange")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.linkRange)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.receiverDiameter = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.receiverDiameter.setObjectName("receiverDiameter")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.receiverDiameter)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.focalLength = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.focalLength.setObjectName("focalLength")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.focalLength)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.opticaTransmittance = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.opticaTransmittance.setObjectName("opticaTransmittance")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.opticaTransmittance)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.darkCurrent = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.darkCurrent.setObjectName("darkCurrent")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.darkCurrent)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.bandwidth = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.bandwidth.setObjectName("bandwidth")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.bandwidth)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.loadResistance = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.loadResistance.setObjectName("loadResistance")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.loadResistance)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.responsivity = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.responsivity.setObjectName("responsivity")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.responsivity)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.visibility = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.visibility.setObjectName("visibility")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.visibility)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.q = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.q.setObjectName("q")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.q)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.solarRadiance = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.solarRadiance.setObjectName("solarRadiance")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.solarRadiance)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.opticalFilterBandwidth = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.opticalFilterBandwidth.setObjectName("opticalFilterBandwidth")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.opticalFilterBandwidth)
        self.pushButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.SpanningRole, self.pushButton)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.beamWaist = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.beamWaist.setObjectName("beamWaist")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.beamWaist)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(20, 50, 231, 16))
        self.label_16.setObjectName("label_16")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(310, 80, 31, 421))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(380, 80, 311, 421))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.areaReceivingLens_AR = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.areaReceivingLens_AR.setObjectName("areaReceivingLens_AR")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.areaReceivingLens_AR)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.receiverBeamDiameter_Dl = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.receiverBeamDiameter_Dl.setObjectName("receiverBeamDiameter_Dl")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.receiverBeamDiameter_Dl)
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.receiverBeamArea_AB = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.receiverBeamArea_AB.setObjectName("receiverBeamArea_AB")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.receiverBeamArea_AB)
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_23.setObjectName("label_23")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.beamDivergenceLoss_Tbdl = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.beamDivergenceLoss_Tbdl.setObjectName("beamDivergenceLoss_Tbdl")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.beamDivergenceLoss_Tbdl)
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.atmosphericExtinctionCoefficient_alpha = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.atmosphericExtinctionCoefficient_alpha.setObjectName("atmosphericExtinctionCoefficient_alpha")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.atmosphericExtinctionCoefficient_alpha)
        self.label_27 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_27.setObjectName("label_27")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.atmosphericTransmittance_Tatm = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.atmosphericTransmittance_Tatm.setObjectName("atmosphericTransmittance_Tatm")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.atmosphericTransmittance_Tatm)
        self.label_29 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_29.setObjectName("label_29")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.receivedPower_PR = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.receivedPower_PR.setObjectName("receivedPower_PR")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.receivedPower_PR)
        self.label_31 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_31.setObjectName("label_31")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.receivingLensFOV = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.receivingLensFOV.setObjectName("receivingLensFOV")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.receivingLensFOV)
        self.label_33 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_33.setObjectName("label_33")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.solidAngle = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.solidAngle.setObjectName("solidAngle")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.solidAngle)
        self.label_35 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_35.setObjectName("label_35")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.receivedsolarPower_Ps = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.receivedsolarPower_Ps.setObjectName("receivedsolarPower_Ps")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.receivedsolarPower_Ps)
        self.label_37 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_37.setObjectName("label_37")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.CurrentDueToSignal_Ir = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.CurrentDueToSignal_Ir.setObjectName("CurrentDueToSignal_Ir")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.CurrentDueToSignal_Ir)
        self.label_39 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_39.setWordWrap(True)
        self.label_39.setObjectName("label_39")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.currentDueToSignalAndSBR_It = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.currentDueToSignalAndSBR_It.setObjectName("currentDueToSignalAndSBR_It")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.currentDueToSignalAndSBR_It)
        self.label_41 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_41.setObjectName("label_41")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.variance_shotCurrentNoise = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.variance_shotCurrentNoise.setObjectName("variance_shotCurrentNoise")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.variance_shotCurrentNoise)
        self.label_43 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_43.setObjectName("label_43")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_43)
        self.variace_darkCurrentNoise = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.variace_darkCurrentNoise.setObjectName("variace_darkCurrentNoise")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.variace_darkCurrentNoise)
        self.label_45 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_45.setObjectName("label_45")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_45)
        self.variance_thermalCurrentNoise = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.variance_thermalCurrentNoise.setObjectName("variance_thermalCurrentNoise")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.variance_thermalCurrentNoise)
        self.label_47 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_47.setObjectName("label_47")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.SNR = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.SNR.setObjectName("SNR")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.SNR)
        self.label_49 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_49.setObjectName("label_49")
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_49)
        self.SNRdB = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.SNRdB.setObjectName("SNRdB")
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.SNRdB)
        LaserCalculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LaserCalculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        LaserCalculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LaserCalculator)
        self.statusbar.setObjectName("statusbar")
        LaserCalculator.setStatusBar(self.statusbar)

        self.retranslateUi(LaserCalculator)
        QtCore.QMetaObject.connectSlotsByName(LaserCalculator)

    def retranslateUi(self, LaserCalculator):
        _translate = QtCore.QCoreApplication.translate
        LaserCalculator.setWindowTitle(_translate("LaserCalculator", "MainWindow"))
        self.label.setText(_translate("LaserCalculator", "Transmittng Power"))
        self.label_2.setText(_translate("LaserCalculator", "Wavelength"))
        self.label_3.setText(_translate("LaserCalculator", "Divergence Angle"))
        self.label_4.setText(_translate("LaserCalculator", "Link Range"))
        self.label_5.setText(_translate("LaserCalculator", "Receiiver Diameter"))
        self.label_6.setText(_translate("LaserCalculator", "focal Lenght"))
        self.label_7.setText(_translate("LaserCalculator", "Optical Transmittance"))
        self.label_8.setText(_translate("LaserCalculator", "Dark Current"))
        self.label_9.setText(_translate("LaserCalculator", "Bandwidth"))
        self.label_10.setText(_translate("LaserCalculator", "Load Resistance"))
        self.label_11.setText(_translate("LaserCalculator", "Responsivity"))
        self.label_12.setText(_translate("LaserCalculator", "Visibility"))
        self.label_13.setText(_translate("LaserCalculator", "q"))
        self.label_14.setText(_translate("LaserCalculator", "Solar Radiance"))
        self.label_15.setText(_translate("LaserCalculator", "Optical Filter Bandwidth"))
        self.pushButton.setText(_translate("LaserCalculator", "Calculate"))
        self.label_18.setText(_translate("LaserCalculator", "Beam Waist"))
        self.label_16.setText(_translate("LaserCalculator", "CALCULATE PARAMETERS"))
        self.label_17.setText(_translate("LaserCalculator", "Area of Receiving Lens (AR)"))
        self.areaReceivingLens_AR.setText(_translate("LaserCalculator", "TextLabel"))
        self.label_19.setText(_translate("LaserCalculator", "Beam Diameter at Receiving Side"))
        self.receiverBeamDiameter_Dl.setText(_translate("LaserCalculator", "TextLabel"))
        self.label_21.setText(_translate("LaserCalculator", "Area of Beam at Receiving Side"))
        self.receiverBeamArea_AB.setText(_translate("LaserCalculator", "TextLabel"))
        self.label_23.setText(_translate("LaserCalculator", "Beam Divergence Loss"))
        self.beamDivergenceLoss_Tbdl.setText(_translate("LaserCalculator", "TextLabel"))
        self.label_25.setText(_translate("LaserCalculator", "Atmospheric Extinction Coefficient"))
        self.atmosphericExtinctionCoefficient_alpha.setText(_translate("LaserCalculator", "TextLabel"))
        self.label_27.setText(_translate("LaserCalculator", "Atmospheric Transmittance"))
        self.atmosphericTransmittance_Tatm.setText(_translate("LaserCalculator", "TextLabel"))
        self.label_29.setText(_translate("LaserCalculator", "Received Power"))
        self.receivedPower_PR.setText(_translate("LaserCalculator", "TextLabel"))
        self.label_31.setText(_translate("LaserCalculator", "Field of View of Receiving Lens"))
        self.receivingLensFOV.setText(_translate("LaserCalculator", "TextLabel"))
        self.label_33.setText(_translate("LaserCalculator", "Solid Angle"))
        self.solidAngle.setText(_translate("LaserCalculator", "TextLabel"))
        self.label_35.setText(_translate("LaserCalculator", "Received Solar Power"))
        self.receivedsolarPower_Ps.setText(_translate("LaserCalculator", "TextLabel"))
        self.label_37.setText(_translate("LaserCalculator", "Current due to Signal"))
        self.CurrentDueToSignal_Ir.setText(_translate("LaserCalculator", "TextLabel"))
        self.label_39.setText(_translate("LaserCalculator", "Current due to Signal and Solar background Radiation"))
        self.currentDueToSignalAndSBR_It.setText(_translate("LaserCalculator", "TextLabel"))
        self.label_41.setText(_translate("LaserCalculator", "Variance of Shot Current Noise"))
        self.variance_shotCurrentNoise.setText(_translate("LaserCalculator", "TextLabel"))
        self.label_43.setText(_translate("LaserCalculator", "Variance of Dark Current Noise"))
        self.variace_darkCurrentNoise.setText(_translate("LaserCalculator", "TextLabel"))
        self.label_45.setText(_translate("LaserCalculator", "Variance of Thermal Current Noise"))
        self.variance_thermalCurrentNoise.setText(_translate("LaserCalculator", "TextLabel"))
        self.label_47.setText(_translate("LaserCalculator", "Signal to Noise Ratio"))
        self.SNR.setText(_translate("LaserCalculator", "TextLabel"))
        self.label_49.setText(_translate("LaserCalculator", "SNR dB"))
        self.SNRdB.setText(_translate("LaserCalculator", "TextLabel"))


